APOTEK/src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from accounts import views
from loginapp.views import logout_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing_page/', include('landing_page.urls', namespace='landing_page')),
    path('homeuser/', lambda request: redirect('/landing_page/', permanent=False)),
    path('homeuser/', include('homeuserapp.urls', namespace="homeuserapp")),
    path('admin_resep/', include('admin_resep.urls')),
    path('admin_daftarobat/', include('admin_daftarobat.urls')),
    path('admin_tambahobat/', include('admin_tambahobat.urls')),
    path('adminapp/', include('adminapp.urls', namespace="adminapp")),
    path('resepapp/', include('resepapp.urls', namespace="resepapp")),
    path('obat/', include('daftarobat.urls')),
    path('logout/', logout_view, name='logout'),
    path('logindjanggo/', LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('uploadresep/',include('uploadresepapp.urls'), name='uploadresepapp'),
    path('riwayat/',include('riwayat.urls'), name='riwayat'),
    path('landing_page/', include('landing_page.urls'), name='landing_page'),
    path('', lambda request: redirect('/landing_page/', permanent=False)),
    #path('', lambda request: redirect('homeuser/')),
    # Remove duplicate include to avoid conflicts
    # path('', include('landing_page.urls')),
    # path('login/', include('accounts.urls', namespace='login')),


    # Redirect dari URL utama (/) ke /homeuser/
    # path('', include('landing_page.urls')),
    # Remove the redirect to 'landing_page/' to avoid double redirect
    # path('', lambda request: redirect('landing_page/'), name='landing_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APOTEK/src/homeuserapp/urls.py
from django.urls import path
from .views import homeuser_view
from django.contrib.auth.views import LoginView


app_name = 'homeuserapp'

urlpatterns = [
    path('', homeuser_view, name='homeuser'),
]

APOTEK/src/resepapp/urls.py
from django.urls import path
from . import views
from .views import homeuser_view



app_name = 'resepapp'

urlpatterns = [
    path('', views.ResepListView.as_view(), name='list'),
    path('create/', views.ResepCreateView.as_view(), name='create'),
    path('<slug:slug>/', views.ResepDetailView.as_view(), name='detail'),
    path('<slug:slug>/edit/', views.ResepUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ResepDeleteView.as_view(), name='resep_delete'),
]

APOTEK/src/resepapp/models.py

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save, pre_save
from .utils import unique_slug_generator
from django.urls import reverse


User = get_user_model()

class ResepDokter(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE)
    nama        = models.CharField(max_length=100,null=True)
    telepon = models.PositiveIntegerField(null=True)
    email       = models.EmailField(max_length=100,null=True)
    foto_resep  = models.ImageField(upload_to='resep_images/')
    catatan     = models.TextField(null=True,blank= True) 
    slug        = models.SlugField(null=True,blank= True, unique=True)


    def __str__(self):
        return f"Resep oleh {self.user.username}"
    
    @property
    def title(self):
        return self.user
    
    def get_absolute_url(self):
        return reverse('resep:detail', kwargs={'slug': self.slug})


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

    #def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
        #print('saved')
        #print(instance.timestamp)

pre_save.connect(rl_pre_save_receiver, sender=ResepDokter)
        #post_save.connect(rl_post_save_receiver, sender=DataObat)

APOTEK/src/resepapp/forms.py
from django import forms
from .models import ResepDokter

class ResepDokterCreateForm(forms.ModelForm):
     class Meta:
        model = ResepDokter
        fields = ['user', 'nama', 'telepon', 'email', 'catatan', 'foto_resep']
        widgets = {
            'user': forms.HiddenInput(),  # Agar tidak tampil di form, tapi bisa di-set di view
        }

APOTEK/src/resepapp/views.py

from django.views.generic import DeleteView ,ListView, DetailView, CreateView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from .models import ResepDokter
from django.shortcuts import render

def homeuser_view( request):
    return render(request, 'resepapp/homeuser.html')

class ResepListView( LoginRequiredMixin,ListView):
    model = ResepDokter
    template_name = 'resepdokter_list.html'

class ResepDetailView( LoginRequiredMixin,DetailView):
    model = ResepDokter
    template_name = 'resepdokter_detail.html'

class ResepCreateView(LoginRequiredMixin, CreateView):
    model = ResepDokter
    fields = ['nama', 'telepon', 'email', 'foto_resep', 'catatan']
    template_name = 'resepapp/form.html'
    success_url = reverse_lazy('homeuserapp:homeuser')

    def form_valid(self, form):
        form.instance.user = self.request.user  # Otomatis isi user
        messages.success(self.request, 'Resep berhasil ditambahkan!')
        return super().form_valid(form)


class ResepUpdateView( LoginRequiredMixin,UpdateView):
    model = ResepDokter
    fields = '__all__'
    template_name = 'resepapp/detail_update.html'
    success_url = reverse_lazy('resepapp:list')

class ResepDeleteView(LoginRequiredMixin, DeleteView):
    model = ResepDokter
    template_name = 'resepapp/resep_delete.html'  # Buat template ini
    success_url = reverse_lazy('resepapp:list')   # Redirect ke daftar resep
    login_url = "/login/"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        nama_pasien = self.object.nama_pasien
        messages.success(request, f"Resep untuk pasien '{nama_pasien}' berhasil dihapus.")
        return super().delete(request, *args, **kwargs)
    

APOTEK/src/resepapp/templates/resepapp/detail_update.html
{% extends "warisan.html" %}
{% block content %}

<h1>Edit Resep</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>

{% endblock %}

APOTEK/src/resepapp/templates/resepapp/form.html
{% extends "warisan.html" %}
{% block content %}

<h1>Form Resep</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Simpan</button>
</form>

{% endblock %}

APOTEK/src/resepapp/templates/resepapp/resep_delete.html
{% extends 'warisan.html' %}
{% block content %}
  <div class="container mt-4">
    <h3>Konfirmasi Hapus</h3>
    <p>Apakah kamu yakin ingin menghapus resep atas nama <strong>{{ object.nama }}</strong>?</p>

    <form method="post">
      {% csrf_token %}
      <a href="{% url 'resepapp:list' %}" class="btn btn-secondary">Batal</a>
      <button type="submit" class="btn btn-danger">Ya, Hapus</button>
    </form>
  </div>
{% endblock %}

APOTEK/src/resepapp/templates/resepapp/resepdokter_detail.html
{% extends "warisan.html" %}
{% block content %}

    <p>{{ object.nama_pasien }}</p>
    {% if object.foto_resep %}
      <img src="{{ object.foto_resep.url }}" alt="Foto Resep" width="200">
    {% else %}
      <p>Tidak ada foto resep</p>
    {% endif %}
    <p>Dokter: {{ object.dokter }}</p>
    <p>Tanggal Resep: {{ object.tanggal }}</p>
    <p>Obat yang Diberikan: {{ object.obat }}</p>
    <p>Catatan: {{ object.catatan }}</p>

{% endblock %}

APOTEK/src/resepapp/templates/resepapp/resepdokter_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.90">
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin_resep/css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'admin_resep/css/styleguide.css' %}" />
    <link rel="stylesheet" href="{% static 'admin_resep/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'admin_resep/css/style_responsive.css' %}" />
  </head>

  <body>
    <div class="resep-admin">
      <div class="nav">
        <div class="magneto-navbar">
          <div class="logo">
            <a href="{% url 'homeuserapp:homeuser' %}">
                <div class="text-wrapper">💊 Apotek Jaya</div>
            </a>
        </div>
        
          <div class="list">
            <div class="component">
              <a href="{% url 'resepapp:list' %}">
                  <div class="text-wrapper-2">Resep Obat</div>
              </a>
          </div>
          <div class="component-false">
              <a href="{% url 'adminapp:list' %}">
                  <div class="text-wrapper-2">Daftar Obat</div>
              </a>
          </div>
          </div>
          <div class="component-2">
            <a href="{% url 'logout' %}">
                <div class="text">LOGOUT</div>
            </a>
        </div>
        </div>

        <div class="text-wrapper-3">Resep Obat</div>
        <div class="frame">
          <div class="frame-2">
        

            <div class="frame-5">
              <div class="frame-4"><div class="table-head">Nama Lengkap</div></div>
              {% for obj in object_list  %}
              <div class="div-wrapper"><div class="table-body">{{ obj.nama }}</div></div>
              {% endfor %}
            </div>

            <div class="frame-6">
              <div class="frame-4"><div class="table-head">Email Address</div></div>
              {% for obj in object_list %}
              <div class="div-wrapper"><div class="table-body">{{ obj.email }}</div></div>
              {% endfor %}
            </div>

            <div class="frame-7">
              <div class="frame-4"><div class="table-head">No Telepon</div></div>
              {% for obj in object_list %}
              <div class="div-wrapper"><div class="table-body">{{ obj.telepon }}</div></div>
              {% endfor %}
            </div>

            <div class="frame-8">
              <div class="frame-4"><div class="table-head">Keluhan</div></div>
              {% for obj in object_list %}
              <div class="div-wrapper"><div class="table-body">{{ obj.catatan }}</div></div>
              {% endfor %}
            </div>

            <div class="frame-9">
              <div class="frame-4">
                <div class="table-head">File Resep</div>
              </div>
            
              {% for obj in object_list %}
              <div class="div-wrapper">
                <div class="table-body-2">
                  <!-- Tombol untuk membuka modal -->
                  <button type="button" class="btn btn-primary open-modal" data-img="{{ obj.foto_resep.url }}" data-toggle="modal" data-target="#fotoModal">Lihat</button>
                </div>
              </div>
            {% endfor %}
            
            <!-- Modal Template -->
            <div class="modal fade" id="fotoModal" tabindex="-1" role="dialog" aria-labelledby="fotoModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="fotoModalLabel">Foto Resep</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <!-- Menampilkan gambar resep -->
                    <img id="modalImage" src="" alt="Foto Resep" class="img-fluid">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                  </div>
                </div>
              </div>
            </div>
            
          
            </div>

            <div class="frame-10">
              <div class="frame-4"><div class="table-head">Hapus</div></div>
              {% for obj in object_list %}
              <div class="div-wrapper">
                <div class="action-buttons">
                  <a href="{% url 'resepapp:resep_delete' obj.slug %}" title="Delete">
                    🗑️
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>
            
          </div>
        </div>
      </div>
    </div>
    {% include 'snippets/js.html' %}
  </body>
</html>